# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenapiChanges < Formula
  desc "The worlds fastest and most scalable OpenAPI linter"
  homepage "https://quobix.com/vacuum"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.3/openapi-changes_0.0.3_darwin_arm64.tar.gz"
      sha256 "683095526e922b345d8e3198a5d9a60322b4f3c80835bd793fbf01cd5fe86e90"

      def install
        bin.install "vacuum"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.3/openapi-changes_0.0.3_darwin_x86_64.tar.gz"
      sha256 "62175e82aa5ac4fe58d50ff139cb065ed338313757ebc1ab17f649cfd3db9de6"

      def install
        bin.install "vacuum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.3/openapi-changes_0.0.3_linux_x86_64.tar.gz"
      sha256 "7daa6368977357fbf2838033a54eb14017a9780657f551a7c82f826e7d49e270"

      def install
        bin.install "vacuum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.3/openapi-changes_0.0.3_linux_arm64.tar.gz"
      sha256 "9fb6170b6a7e29b3cbbb7ecfc6f62094eee1314c11320d8e3ab60dafd8ced05d"

      def install
        bin.install "vacuum"
      end
    end
  end
end
